[package]
name = "docgraph-cozo"
description = "Private Cozo adapter for docgraph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
cozo.workspace = true
docgraph-core.workspace = true
docgraph-markdown.workspace = true
toml_edit.workspace = true
