[souffle]
repository = "https://github.com/souffle-lang/souffle.git"
revision = "a1303be3c0166400dee3d1f36f0d96abe03e6901"

[vcpkg]
repository = "https://github.com/microsoft/vcpkg.git"
revision = "cd61e1e26a038e82d6550a3ebbe0fbbfe7da78e3"
triplet = "x64-windows-static"
packages = ["sqlite3"]

[winflexbison]
version = "2.5.25"
url = "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
sha256 = "8d324b62be33604b2c45ad1dd34ab93d722534448f55a16ca7292de32b6ac135"

[artifact.windows-x86_64]
name = "docgraph-logic-runtime.exe"
features = ["64-bit-domain", "sqlite", "static-crt"]

[artifact.linux-x86_64]
name = "souffle"
version = "2.5"
url = "https://github.com/souffle-lang/souffle/releases/download/2.5/x86_64-ubuntu-2404-souffle-2.5-Linux.deb"
sha512 = "6b86e554f6aa5abf8a8b55d8312ae37c0957c5bd6c9edeea89246db9406f645ec5e600b84fe6636b1c163da556f0da6c3d2dad46c1083413f2fcf4f95b9ac62c"
features = ["64-bit-domain", "sqlite"]
